### ISSUE TITLE
Fontsubsetting causes Arabic copy to change in characters

### ISSUE THREAD

**Issue by mm-paulie** [mediamonks/display-dev-server#31]
normal
![image (1)](https://user-images.githubusercontent.com/45459258/170069573-67b31ed8-6594-47c1-babb-bbe2e7027645.png)

with font subsetting:
![image](https://user-images.githubusercontent.com/45459258/170069579-d7be95df-71e9-4161-abeb-7be960c1f6b0.png)

 also see project mondelez-menap-tang-everyday-amazing-kids-gcc

**Comment by mirkovw** [comment]
@mm-paulie I mentioned this issue in the repository of subset-font, which is the npm package we use for subsetting in the framework, and it looks like this was mainly a font issue. Doesn't have anything to do with our implementation of font subsetting in the framework.

https://github.com/papandreou/subset-font/issues/17

Going to close this issue for now.
