### ISSUE TITLE
inline SVG removes the id's from the original SVG

### ISSUE THREAD

**Issue by PabloCarreira** [mediamonks/display-dev-server#38]
@alandawi @mirkovw @mm-paulie 
Hi Team! 
me again. 
Not urgent cause there is a simple solution to this by not using the util and writing the svg inline, But
I am learning if it is a feature I don't understand how to use correctly or if something changed in the last update.

The issue is that inline is working as usual on previews versions, but now is deleting the IDs on the SVG file

I am trying to understand how it works and this is how far I got. might be that [this file](https://github.com/mediamonks/display-dev-server/blob/885c584c2e5181b73c26b5e04f666a7ad02ee35b/src/webpack/plugin/HtmlWebpackInlineSVGPlugin.js#L581) is not being used? and where is the actual inline working after compilation?

Sorry if am not being clear, happy to jump on a call and show the issue.
I'll keep looking into it
Thanks

**Comment by alandawi** [comment]
1) Why do we have the inlineSvg Util (temple) if by default we have a plugin in Webpack that does the same thing?

2) After looking at the svgo package structure, I notice that `svgo.js` expects the plugins as an array. I made the following change to the file `HtmlWebpackInlineSVGPlugin.js` and it works fine.

Replace:

`const result = SVGO.optimize(data, {
        cleanupIDs: false
    });`

To:

`const result = SVGO.optimize(data, {
    plugins: [
        {
            name: 'preset-default',
            params: {
                overrides: {
                    cleanupIDs: false
                },
            },
        },
    ],
});`

**Comment by mirkovw** [comment]
Hey @PabloCarreira and @alandawi,
Thanks for pointing this out and thanks @alandawi for providing the fix straight away! Do you want to do the honors and create a PR?

@alandawi regarding your first point - I don't know to be honest. Perhaps we can discuss whether we still need it on our next dev call

**Comment by mm-paulie** [comment]
It might still be handy when you want to politely load your svg's instead of injecting them in the html directly via webpack. Say for instance, if I want to pick one or another svg based on some dynamic data. Then I first need to load in dynamic data and afterwards load the chosen svg?

**Comment by alandawi** [comment]
@mm-paulie Thanks for the explanation. I will update the 'svg guide' with the default inline and also using the inlineSvg Util.

@PabloCarreira Can you take the responsability to create a fork and push a PR?

**Comment by PabloCarreira** [comment]
Thanks, guys! Will do. 
My first fork of the framework, what moment to be alive
