### ISSUE TITLE
Add timeline control on each banner preview

### ISSUE THREAD

**Issue by Cinterella** [mediamonks/display-dev-server#52]
@alandawi @mirkovw @mm-paulie

Hey team!

Not urgent cause is not an issue, but I think this will improve the way we tests our banners.

Can we add the timeline control for each unit as we had on previous versions?
Using like this: http://localhost:8000/src_300x250/index.html?gsdevtools=true

This way we'll have extra information like:
- Total duration
- Banner position will be 0,0 (that is easy to add layers to match images for pixel perfect projects)

Thanks in advance,

Cin

**Comment by mm-paulie** [comment]
Locally you can do this, by just uncommenting the timelineScrubber now in the newest display-boilerplate-template. 
```
if (DEVELOPMENT) {
  timelineScrubber(this.animation.getTimeline());
}
```


You could add the timelineScrubber in the production phase by leaving out the if DEVELOPMENT statement in Banner.js here:
```
//if (DEVELOPMENT) {
  timelineScrubber(this.animation.getTimeline());
//}
```

However, keep in mind that by doing this, the timelineScrubber will be implemented in the build files, you don't want to send this to the client, only use this for online testing purposes when needed.
