### ISSUE TITLE
Issue with unique 'googlesheets' names when you have multiple richmediaRCs within same folder

### ISSUE THREAD

**Issue by mirkovw** [mediamonks/display-dev-server#57]
For example if you have 
/src/300x250/richmediarc.photo
/src/300x250/richmediarc.illustration

if there is a feed connected to these with let's say 4 rows,
you will get 8 banners to choose from.
But the 'googlesheets' filenames for the last 4 will not be unique and will get placed in the root folder

**Comment by mirkovw** [comment]
Potentially, yes. Depends on your setup..

Do you have rows that are only meant for certain sizes or versions? Then yes you need a filter.

Otherwise, without filtering, each config that has a content source will receive configs for each row that's in the feed

**Comment by alandawi** [comment]
![Captura de Pantalla 2022-07-16 a la(s) 15 05 24](https://user-images.githubusercontent.com/1291730/179367000-dc6fc193-50fd-4ee8-9fe3-e193dc79ed1f.png)

I understand. So in this case then I don't think it's a good idea to use a sheet for this structure

**Comment by mirkovw** [comment]
I'm not sure what the scope of the project is but perhaps if you just add a filter for size it will be more manageable? 

I'm on holiday for the next two weeks so perhaps @mm-paulie can chime in here?
