### ISSUE TITLE
DCO expose generated code and ID profile to builded units

### ISSUE THREAD

**Issue by PabloCarreira** [mediamonks/display-dev-server#63]
I am thinking of a way to expose or facilitate the manipulation of the generated code and ID profile to already-built units with the DCO template.

The idea is to facilitate the traffickers to change profile ID and generated code to match new profiles for different language distribution.

I know this is a potential issue generator cause a small change in a name in the dynamic elements will brake the banner. But the possibility to change that will release the traffick team to have to know how to use the framework and build units

**Comment by mirkovw** [comment]
Hey Pablo , interesting! I'd like to hear more about this if you're up for a chat?

**Comment by mm-paulie** [comment]
@PabloCarreira are you still in with this idea? Would you like to explain it to me?

**Comment by PabloCarreira** [comment]
@mm-paulie Sorry for the late reply Paulie, But this is no longer a good Idea. 
Closing the Issue
