### ISSUE TITLE
Download button in preview sometimes doesn't work

### ISSUE THREAD

**Issue by mirkovw** [mediamonks/display-dev-server#8]
As seen in this preview
http://richmedia-previews-s3bucket-tu6a9uv81tss.s3.amazonaws.com/5ed9c8f7-7680-40bd-9ce9-115cbe21f8fd/tme-bmw-mini-belux-brussels-motorshow-edition-2/v1/index.html

**Comment by Trung-Dev** [comment]
@mirkovw fixed can you check and merge

**Comment by mirkovw** [comment]
fixes #8
