### ISSUE TITLE
Get rid of the blue line above each banner

### ISSUE THREAD

**Issue by mm-paulie** [mediamonks/display-dev-server#88]
Currently we have a blue line above each banner. This doesn't always look great with each design.  I would suggest to remove it to not have a conflicting style:
![remove_line](https://github.com/mediamonks/display-dev-server/assets/45459258/56c286c6-f3da-4607-9cb9-ba7fdfabda8b)

It's the .MuiTabs-indicator

**Comment by mm-vasyl** [comment]
This line makes sense when we have a couple of outputs:
![image](https://github.com/mediamonks/display-dev-server/assets/106164207/a88e7e54-fcfb-4696-ab21-c646ea09a75d)

https://richmedia-previews-s3bucket-tu6a9uv81tss.s3.amazonaws.com/be555562-109f-4bbd-8590-5e533365522g/index.html?filter=

We can either try to remove the line when we have only HTML on the page or redesign "active tab" effect at all

**Comment by mm-paulie** [comment]
You are right, I just got the question a couple of times now already to remove it haha. When we have only one output no line would make sense, yes.
