### ISSUE TITLE
Option to prevent SVGO to merge elements from svg when inline executes

### ISSUE THREAD

**Issue by PabloCarreira** [mediamonks/display-dev-server#95]
https://github.com/mediamonks/display-dev-server/blob/486e8dcd12ddc6955bc03cc5f5979f89875315ad/src/webpack/plugin/HtmlWebpackInlineSVGPlugin.js#L457

So I was working with the inlinbe feature, which is great to load dinamic svg elements and inject them into the HTML to access them through JS and animate everything inside it. 
But I was bumping with an issue that the config we have ATM it merges all path elements into one, which for some cases are not ideal because we need to grab diferent path elements and animate them. 

I found a simple solution to just not merge and add this config to the line above`mergePaths:false,` 

Lets talk about the pro's and Con's of not merging them at all, or if we need to refactor a bit more and give the option for it.

**Comment by mm-paulie** [comment]
Can you give/show me which svg caused this issue? I tried to replicate the issue by creating an svg with paths, but I didn't notice any issues.

**Comment by mm-vasyl** [comment]
I'd love to look into the original issue/cause of the issue too!
Can't replicate on my end either
